doctrine_migrations:
    migrations_paths:
        'App\Hello\Infrastructure\Persistence\Doctrine\Migration': '%kernel.project_dir%/src/Hello/Infrastructure/Persistence/Doctrine/Migration'
    enable_profiler: false
