doctrine_migrations:
    migrations_paths:
        'App\News\Infrastructure\Persistence\Doctrine\Migration': '%kernel.project_dir%/src/News/Infrastructure/Persistence/Doctrine/Migration'
    enable_profiler: false
