parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Hello/Domain/Entity/'
      - '../src/Kernel.php'

  App\Hello\Domain\Repository\HelloRepositoryInterface:
    alias: 'App\Hello\Infrastructure\Persistence\Doctrine\Repository\HelloWorldEntityRepository'
