openapi: 3.0.0
info:
  title: 'APP API'
  version: '1.0'
servers:
  -
    url: 'http://localhost:8080'
    description: 'Local server'
paths:
  /api/v1/news:
    post:
      tags:
        - News
      summary: News
      operationId: App\News\Infrastructure\Api\V1\Controller\NewsController
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewsRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsResponse'
components:
  schemas:
    NewsRequest:
      properties:
        page:
          type: integer
          default: '1'
          example: '1'
          nullable: false
        perPage:
          type: integer
          default: '10'
          example: '10'
          nullable: false
        day:
          type: string
          default: today
          example: '2023-02-10'
          nullable: true
      type: object
    NewsItemResponse:
      required:
        - id
        - createdAt
      properties:
        id:
          type: string
          format: uuid
          nullable: false
        title:
          type: string
          nullable: false
        short:
          type: string
          nullable: false
        content:
          type: string
          nullable: false
        day:
          type: string
          format: date
          nullable: false
        time:
          type: string
          format: time
          nullable: false
        image:
          type: string
          format: url
          nullable: true
      type: object
    NewsResponse:
      required:
        - createdAt
      properties:
        total:
          type: string
          format: datetime
          example: '2021-01-03T02:30:00+01:00'
          nullable: false
        items:
          type: array
          items:
            $ref: '#/components/schemas/NewsItemResponse'
          nullable: false
      type: object
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  -
    bearerAuth: []
